// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalentToolSystem.Services.DemandAPI.Data;

#nullable disable

namespace TalentToolSystem.Services.DemandAPI.Migrations
{
    [DbContext(typeof(DemandContext))]
    [Migration("20230925065539_Initial2")]
    partial class Initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalentToolSystem.Services.DemandAPI.Model.Demand", b =>
                {
                    b.Property<int?>("DemandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("DemandId"));

                    b.Property<string>("Account_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DemandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxBudget")
                        .HasColumnType("int");

                    b.Property<int>("NoticePeriod")
                        .HasColumnType("int");

                    b.Property<int>("OpenPosition")
                        .HasColumnType("int");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DemandId");

                    b.ToTable("demands");

                    b.HasData(
                        new
                        {
                            DemandId = 1,
                            Account_Name = "Amazon",
                            DemandName = "Python Developer",
                            Email = "nexturn@gmail.com",
                            EmployeeType = "FTE",
                            Experience = 1,
                            Location = "Hyderabad",
                            Manager = "Gunjan",
                            MaxBudget = 10,
                            NoticePeriod = 2,
                            OpenPosition = 1,
                            Skills = "C++,.Net,Sql Server",
                            Status = "Selected"
                        },
                        new
                        {
                            DemandId = 2,
                            Account_Name = "Amazon",
                            DemandName = "Java Developer",
                            Email = "nexturn@gmail.com",
                            EmployeeType = "FTE",
                            Experience = 1,
                            Location = "Hyderabad",
                            Manager = "Gunjan",
                            MaxBudget = 10,
                            NoticePeriod = 2,
                            OpenPosition = 1,
                            Skills = "C++,.Net,Sql Server",
                            Status = "Selected"
                        },
                        new
                        {
                            DemandId = 3,
                            Account_Name = "Amazon",
                            DemandName = ".Net Developer",
                            Email = "nexturn@gmail.com",
                            EmployeeType = "FTE",
                            Experience = 1,
                            Location = "Hyderabad",
                            Manager = "Gunjan",
                            MaxBudget = 10,
                            NoticePeriod = 2,
                            OpenPosition = 1,
                            Skills = "C++,.Net,Sql Server",
                            Status = "Selected"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
