// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalentToolSystem.Services.CandidateAPI.Data;

#nullable disable

namespace TalentToolSystem.Services.CandidateAPI.Migrations
{
    [DbContext(typeof(CandidateContext))]
    [Migration("20230921044446_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalentToolSystem.Services.CandidateAPI.Model.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CandidateId"));

                    b.Property<decimal>("CTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentCompany")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ECTC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoticePeriod")
                        .HasColumnType("int");

                    b.Property<string>("SkillSet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearOfExperience")
                        .HasColumnType("int");

                    b.HasKey("CandidateId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            CandidateId = 1,
                            CTC = 10m,
                            CandidateName = "Indresh Kumar Maurya",
                            CurrentCompany = "Nexturn",
                            ECTC = 10m,
                            Email = "indresh@gmail.com",
                            EmployeeID = 101,
                            Location = "Mirzapur",
                            Mobile = "7823637281",
                            NoticePeriod = 10,
                            SkillSet = "C++,.Net,Sql Server",
                            Status = "Selected",
                            YearOfExperience = 1
                        },
                        new
                        {
                            CandidateId = 2,
                            CTC = 10m,
                            CandidateName = "Shobhit Kumar Singh",
                            CurrentCompany = "Nexturn",
                            ECTC = 10m,
                            Email = "shobhit@gmail.com",
                            EmployeeID = 101,
                            Location = "Patna",
                            Mobile = "7823637281",
                            NoticePeriod = 10,
                            SkillSet = "C++,.Net,Sql Server",
                            Status = "Selected",
                            YearOfExperience = 1
                        },
                        new
                        {
                            CandidateId = 3,
                            CTC = 10m,
                            CandidateName = "Abuzar Nasim",
                            CurrentCompany = "Nexturn",
                            ECTC = 10m,
                            Email = "abuzar@gmail.com",
                            EmployeeID = 101,
                            Location = "Ranchi",
                            Mobile = "7823637281",
                            NoticePeriod = 10,
                            SkillSet = "C++,.Net,Sql Server",
                            Status = "Selected",
                            YearOfExperience = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
